name: Ubuntu Build SL

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Cargo Registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ubuntu-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo-deb
        run: cargo install cargo-deb
      - name: Install cross-compilation toolchain
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}
      - name: Build Release
        run: |
          if [ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]; then
            export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
          fi
          COMPLETION_DIR="$(pwd)/completions" cargo build --release --target=${{ matrix.target }}
      - name: Build .deb Package
        id: deb_build
        run: |
          cargo deb --manifest-path=apps/sl/Cargo.toml --target=${{ matrix.target }} --no-build
          DEB_FILE=$(ls target/debian/sl_*.deb)
          echo "deb_file=${DEB_FILE}" >> $GITHUB_OUTPUT
          echo "deb_name=$(basename ${DEB_FILE})" >> $GITHUB_OUTPUT
      - name: Test .deb Package
        run: |
          dpkg -I ${{ steps.deb_build.outputs.deb_file }}
          dpkg -c ${{ steps.deb_build.outputs.deb_file }}
      - name: Upload .deb Package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.deb_build.outputs.deb_name }}
          path: ${{ steps.deb_build.outputs.deb_file }}
